name: telegram_userbot_lifetime_apis
description: A Library Full Package Template
version: 0.0.0
homepage: https://github.com/azkadev/telegram_userbot_lifetime
repository: https://github.com/azkadev/telegram_userbot_lifetime
issue_tracker: https://github.com/azkadev/telegram_userbot_lifetime/issues 
documentation: https://youtube.com/@azkadev
funding:
  - https://github.com/sponsors/azkadev


platforms:
 android:
 ios:
 linux:
 macos:
 web:
 windows:
 
environment:
  sdk: ^3.2.3

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
